### ISSUE TITLE
Вёрстка в окне уведомлений

### ISSUE THREAD

**Issue by dankinescop** [communcom/support#4]
Длинные ссылки "ломают" страницу в окне уведомлений

![image](https://user-images.githubusercontent.com/32875649/71972781-76195200-321e-11ea-9a26-de0748c47e4f.png)

**Comment by daryasattarova** [comment]
![image](https://user-images.githubusercontent.com/42342756/73245828-3bbc2880-41be-11ea-8f4d-61c4546840ff.png)
