### ISSUE TITLE
Не отображаются авторы постов в proposals на бан 

### ISSUE THREAD

**Issue by chinpu** [communcom/support#7]
Отображаются лишь имена авторов, предложивших бан

![IMG_6455](https://user-images.githubusercontent.com/31181445/72887923-a7654800-3d1d-11ea-9eac-386efd021b43.jpg)

**Comment by daryasattarova** [comment]
если это поведение верно, то они до сих пор не отображаются.

**Comment by NickShtefan** [comment]
Issue moved to [communcom/prism #379](https://github.com/communcom/prism/issues/379) via [**ZenHub**](https://www.zenhub.com/)
